[run]
init_cmds = [
	["make"],
	["./gowalker"]
]
watch_all = true
watch_dirs = [
	"$WORKDIR/conf/locale",
	"$WORKDIR/models",
	"$WORKDIR/modules",
	"$WORKDIR/routers"
]
watch_exts = [".go"]
build_delay = 1500
cmds = [
	["make"],
	["./gowalker"]
]